const main = async () => {
  
}

main()
  .then()
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
